"""Registre des mini-TB sim_tests : un seul endroit à maintenir.

Par test : sources, defines, plusargs, timeout (s), regex de verdict.
Le verdict est une ligne `TNN PASS` / `TNN FAIL ...` affichée par le TB.
"""
import re

TESTS = {
    "t01": {
        "name": "t01_dqs_law",
        "dir": "t01_dqs_law",
        "tb": "tb_t01.v",
        "includes": ["simulation", "sim_tests/common"],
        "defines": [],
        "plusargs": [],
        "timeout": 120,
        "verdict": re.compile(r"^T01 (PASS|FAIL)"),
    },
    "t02": {
        "name": "t02_dqsw_law",
        "dir": "t02_dqsw_law",
        "tb": "tb_t02.v",
        "includes": ["simulation", "sim_tests/common"],
        "defines": [],
        "plusargs": [],
        "timeout": 120,
        "verdict": re.compile(r"^T02 (PASS|FAIL)"),
    },
    "t03_23": {
        "name": "t03_write_anchor(step=23)",
        "dir": "t03_write_anchor",
        "tb": "tb_t03.v",
        "sources": ["simulation/ddr3_vanilla.v", "hw/gen/Ddr3ControllerSim.v",
                    "simulation/prim_sim_tb.v"],
        "includes": ["simulation"],
        "defines": ["SIM", "den1024Mb", "sg25", "x16"],
        "plusargs": ["step=23"],
        "timeout": 3600,
        "verdict": re.compile(r"^T03 (PASS|FAIL)"),
    },
    "t03_25": {
        "name": "t03_write_anchor(step=25)",
        "dir": "t03_write_anchor",
        "tb": "tb_t03.v",
        "sources": ["simulation/ddr3_vanilla.v", "hw/gen/Ddr3ControllerSim.v",
                    "simulation/prim_sim_tb.v"],
        "includes": ["simulation"],
        "defines": ["SIM", "den1024Mb", "sg25", "x16"],
        "plusargs": ["step=25"],
        "timeout": 3600,
        "verdict": re.compile(r"^T03 (PASS|FAIL)"),
    },
    "t05_23": {
        "name": "t05_wl_anchor(step=23)",
        "dir": "t05_wl_anchor",
        "tb": "tb_t05.v",
        "sources": ["simulation/ddr3_vanilla.v", "hw/gen/Ddr3ControllerSim.v",
                    "simulation/prim_sim_tb.v"],
        "includes": ["simulation"],
        "defines": ["SIM", "den1024Mb", "sg25", "x16"],
        "plusargs": ["step=23"],
        "timeout": 600,
        "verdict": re.compile(r"^T05 (PASS|FAIL)"),
    },
    "t05_25": {
        "name": "t05_wl_anchor(step=25)",
        "dir": "t05_wl_anchor",
        "tb": "tb_t05.v",
        "sources": ["simulation/ddr3_vanilla.v", "hw/gen/Ddr3ControllerSim.v",
                    "simulation/prim_sim_tb.v"],
        "includes": ["simulation"],
        "defines": ["SIM", "den1024Mb", "sg25", "x16"],
        "plusargs": ["step=25"],
        "timeout": 600,
        "verdict": re.compile(r"^T05 (PASS|FAIL)"),
    },
    "t04": {
        "name": "t04_read_rpoint",
        "dir": "t04_read_rpoint",
        "tb": "tb_t04.v",
        "sources": ["simulation/ddr3_vanilla.v", "hw/gen/Ddr3ControllerSim.v",
                    "simulation/prim_sim_tb.v"],
        "includes": ["simulation"],
        "defines": ["SIM", "den1024Mb", "sg25", "x16"],
        "plusargs": ["step=25"],
        "timeout": 1800,
        "verdict": re.compile(r"^T04 (PASS|FAIL)"),
    },
}
